samik_dbt_warehouse:
  outputs:
    dev:
      account: pn67968.west-us-2.azure
      database: RAW_EXTRACT
      password: Argentina@2022
      role: Accountadmin
      schema: PUBLIC
      threads: 2
      type: snowflake
      user: samba
      warehouse: COMPUTE_WH
  target: dev
