samik_dbt_warehouse:
  outputs:
    dev:
      account: yw21262.us-east-2.aws
      database: TEST_SNOWFLAKE
      password: Messi@2022
      role: USER2
      schema: PUBLIC
      threads: 2
      type: snowflake
      user: bhattacha2
      warehouse: DBT_WH
  target: dev
