samik_dbt_warehouse:
  outputs:
    dev:
      account: th84028.west-us-2.azure
      database: RAW_EXTRACT
      password: Rishik@191019
      role: Accountadmin
      schema: PUBLIC
      threads: 2
      type: snowflake
      user: sambha
      warehouse: COMPUTE_WH
  target: dev
